### ISSUE TITLE
Steaming Api's returing maps

### ISSUE THREAD

**Issue by saltperfect** [g8rswimmer/go-twitter#100]
Hi, I was wondering why Functions like `FilteredStream`, https://github.com/g8rswimmer/go-twitter/blob/aa7833ab9c275b0e89ea752e9d7735dc4d042935/tweet.go#L515
or `SampledStream` https://github.com/g8rswimmer/go-twitter/blob/aa7833ab9c275b0e89ea752e9d7735dc4d042935/tweet.go#L554 are returning maps instead of channels? 

Is it possible to change it so that it start's returning a channel and function, maybe a Stop function, when called we could close the channel?

Any other suggestions?

**Comment by g8rswimmer** [comment]
@saltperfect 
I would recommend look at `v2` of the library.  I did a better job of understanding the needs for the streams.  

The new streams return a stream object (https://github.com/g8rswimmer/go-twitter/blob/master/v2/tweet_stream.go#L158).  The streaming object has the following:
* buffered channels for `tweets` and `system messages`
* non-blocking handling
* method `Connection` to determine if the stream is still alive
* method `Close` to stop the stream

`v2` also has some better examples as well.
* [sample stream](https://github.com/g8rswimmer/go-twitter/blob/master/v2/_examples/tweet-sample-stream/main.go)
* [filtered stream](https://github.com/g8rswimmer/go-twitter/blob/master/v2/_examples/tweet-search-stream/main.go)

This should address your concerns.

**Comment by saltperfect** [comment]
Got it!! Thanks. I will take a lot at v2 apis.
