### ISSUE TITLE
Rate limit handling

### ISSUE THREAD

**Issue by tigerschweinekater** [g8rswimmer/go-twitter#102]
Is there already an implementation for handling rate limits (v2)?  
I'm thinking of using the `x-rate-limit-reset` HTTP header to trigger an automatic waiting period, similar to what [tweepy](https://github.com/tweepy/tweepy) does.
Unfortunately, at least for `UserLookupResponse` there is no meta object yet.

**Comment by g8rswimmer** [comment]
I am not sure if the library should handle the rate limiting, but I think that the requests should return the rate limit information to allow the application to handle that information as it would see fit.

https://developer.twitter.com/en/docs/twitter-api/rate-limits

**Comment by Guitarbum722** [comment]
Totally agree, @g8rswimmer - any handling would be a huge assumption IMO, much like the handling of pagination by the lib.

**Comment by tigerschweinekater** [comment]
Wow you guys are real quick! I did not mention it before, but this is a really cool project!

As @Guitarbum722 mentioned, handling the rate limits would be a convenience feature just like handling pagination.
This is surely nice to have, but very optional.

Essential is, as @g8rswimmer mentioned, returning the rate limit information, so that should be the minimum goal.

**Comment by g8rswimmer** [comment]
I am going to add this to the next milestone to address this.

**Comment by tigerschweinekater** [comment]
Perfect, thank you!
Such nice-to-have convenience features (e.g., handle pagination or handle rate limits) sure do imply huge assumptions and they might not be good defaults, but they could be great candidates for wrappers provided by the library, because I'm sure it's better to implement such logic correct once instead of having X applications implementing it wrong.
