### ISSUE TITLE
Connection Lost consistently On Filtered tweet stream

### ISSUE THREAD

**Issue by saminahbab** [g8rswimmer/go-twitter#141]
I am trying to start a real time ongoing stream with one rule.
Creation of the rule does not throw errors, and the rule registers. 

My main stream code looks like this: 

```
client := &twitter.Client{
		Authorizer: Authorize{
			Token: config.TWITTER_TOKEN,
		},
		Client: http.DefaultClient,
		Host:   "https://api.twitter.com",
	}

	options := twitter.TweetSearchStreamOpts{
		TweetFields: []twitter.TweetField{
			twitter.TweetFieldCreatedAt,
			twitter.TweetFieldEntities,
			twitter.TweetFieldAuthorID,
			twitter.TweetFieldText,
			twitter.TweetFieldID,
			twitter.TweetFieldConversationID,
		},
		UserFields: []twitter.UserField{
			twitter.UserFieldDescription,
			twitter.UserFieldURL,
			twitter.UserFieldName,
			twitter.UserFieldVerified,
		},
		Expansions: []twitter.Expansion{},
	}

	tweetStream, err := client.TweetSearchStream(ctx, options)
	if err != nil {
		return nil, err
	}

	te.Stream = tweetStream
```

Here is the code to retrieve the tweets: 

```
for {
		select {

		case tm := <-te.Stream.Tweets():
			for _, tweet := range tm.Raw.Tweets {
				message := ParseMessage(tweet)
				channel <- message
			}

		case sm := <-te.Stream.SystemMessages():
			smb, _ := json.Marshal(sm)
			log.Println("System Message")
			log.Println(smb)

		case strErr := <-te.Stream.Err():
			log.Println("Stream Error")
			log.Println("Error -> ", strErr)
			break

		case shouldBreak, _ := <-te.ShutdownChannel:
			// Graceful Exit signal
			if shouldBreak {
				break
			}

		default:
		}

		if te.Stream.Connection() == false {
			fmt.Println("connection lost")
			break
		}
	}
```

The problem, within thirty seconds of starting the program, the streamer returns "connection lost" and exits. This happens every time. Have you seen similar behaviour before?

**Comment by saminahbab** [comment]
No I do not have a timeout. 
I use context.Background()
Also, just now tried to use the [example script](https://github.com/g8rswimmer/go-twitter/blob/master/v2/_examples/tweets/filtered-stream/tweet-search-stream-delete-rules/main.go) provided with my token. 

I get the same error
```
> go run .
Callout to tweet search stream callout
connection lost
```

So a bit confused as to how to keep the connection persistent.

**Comment by BerndCzech** [comment]
Hi there, I have the same `connection lost` issue. I will also have another look within the next week.
But anyways the best v2 API client i came across. gj!

**Comment by g8rswimmer** [comment]
Something to remember is that the stream APIs from twitter are using long lived REST connections.  Those connections may be disconnected (it is also subject to rate limiting as well). Documentation [here](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data).

I believe that the streaming [API](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream) as a back fill option to allowing for stream to pickup where it left off.

If you can provide some examples of what you are seeing, I could try and reproduce but without anything like that, we might end up with the old _it works on my machine_.

**Comment by saminahbab** [comment]
> No I do not have a timeout. I use context.Background() Also, just now tried to use the [example script](https://github.com/g8rswimmer/go-twitter/blob/master/v2/_examples/tweets/filtered-stream/tweet-search-stream-delete-rules/main.go) provided with my token.
> 
> I get the same error
> 
> ```
> > go run .
> Callout to tweet search stream callout
> connection lost
> ```
> 
> So a bit confused as to how to keep the connection persistent. Can I please confirm that this does not happen for you, with the example script?

@g8rswimmer I have mentioned here that the example script that I linked leads to the same kind of connection lost issues, would you expect that the stream APIs from twitter maybe disconnected in the same twitter disconnections that you mention? 
If you could confirm that the example script works for you without being disconnected within a minute consistently, that would be a good start for me (as it is not working for me)

**Comment by saminahbab** [comment]
Hello @g8rswimmer, Can I confirm that the above solution would be the intended way to use the stream, as proposed by @BerndCzech ? IE 
`logger.Warn("client got disconnected")
			time.Sleep(time.Second)
			//tweetStream, err = client.TweetSearchStream(ctx, opts)
			//if err != nil {
			//	return errors.Errorf("tweet sample callout error: %v", err)
			//}`
So just sleep for a second, do not retry to reconnect (code is commented out), and just go on the for loop? 

The reason I ask is because your sample code shows this: 
```
			default:
			}
			if tweetStream.Connection() == false {
				fmt.Println("connection lost")
				return
			}
```
suggesting that you do need to handle the reconnection in some kind of way. If so, could you suggest a reasonable way to handle the reconnection without hitting ratelimits and using the backfill? 

Thank you for your time!

**Comment by calehh** [comment]
@g8rswimmer @BerndCzech Heartbeat timeout may be too short.
According to Twitter API v2 [docs](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/handling-disconnections): "The endpoint provides a 20-second keep alive heartbeat (it will look like a new line character). ".  
So it seems like the constant `keepAliveTO = 11 * time.Second` is too short. It's better to wait at least 20s before decide that we are disconnected.
Set constant `keepAliveTO` more than 20 seconds and try to reconnect instead of simply break.

**Comment by g8rswimmer** [comment]
@calehh 
Of course twitter is not updating their documentation or making sure that it references the updated document.  This was the [doc](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data) that I used, which states a 10 second heartbeat.
