### ISSUE TITLE
Using library with OAuth 1.0 user context authorization

### ISSUE THREAD

**Issue by ingwar1991** [g8rswimmer/go-twitter#15]
It's been a pleasure using library with oauth 2.0 bearer token authorization. Great job!

Now I'm trying to get responses with oauth1.0 for api v2 as described here
> https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets

As I understand I just need to write new authorize struct, that will use oauth1.0
> type authorize struct {
> 	Token string
> }
> func ( a authorize ) Add( req *http.Request ) {
> 	req.Header.Add( "Authorization", fmt.Sprintf( "Bearer %s", a.Token ) )
> }

Found several oauth1.0 implementation like this
> github.com/dghubble/oauth1

They all seem to provide authorization logic through http.Client

So I've tried to use client from this lib but it didn't work
>	twAppConfig := oauth1.NewConfig(CONSUMER_KEY, CONSUMER_SECRET)
>	token := oauth1.NewToken(TOKEN, TOKEN_SECRET)
>	httpClient := twAppConfig.Client(oauth1.NoContext, token)
>
>	tweet := &twitter.Tweet{
>		Authorizer: authorize{},
>		Client: httpClient, 
>		Host:   "https://api.twitter.com",
>	}

Writing custom oauth implementation for this case doesn't seem right, so I believe there is a way to use the existing solutions, that I just don't see

Please help :)

**Comment by g8rswimmer** [comment]
In your example what is your `authorize` structure?

I think for the case of using the `oath1` library, you would want the structure to look something like this.
```
type authorize struct {
}

func (a authorize) Add(req *http.Request) {

}
```

So the authorize will not add anything to the http request headers as the `oath1` library will be taking care of that.

Hopefully this helps...

**Comment by ingwar1991** [comment]
Yes, used empty struct & Add() func

I think I've found the issue

> fieldOpts := twitter.TweetFieldOptions{
> 		TweetFields: []twitter.TweetField{
> 			twitter.TweetFieldPublicMetrics,
> 			twitter.TweetFieldOrganicMetrics,
> 			twitter.TweetFieldNonPublicMetrics,
> 			twitter.TweetFieldPromotedMetrics, // this creates problems
> 		},
> 	}
> 
> lookups, err := tweet.Lookup(context.Background(), tweetIds, fieldOpts)
> fmt.Println(lookups, err)


When I'm using twitter.TweetFieldPromotedMetrics field, both result & error are empty
> `map[] <nil>`

If I remove the `twitter.TweetFieldPromotedMetrics` field, it works perfectly
This makes sense, because all the tweets in query weren't promoted with an Ad

Situation repeats, when I switch to OAuth2.0 authorization( through Token ) and include `twitter.TweetFieldNonPublicMetrics` field, that requires OAuth1.0. Again both result & error are empty
> `map[] <nil>`

Data returns when remove fields, that require OAuth1.0 authorization

It would be great to get some error explaining, that inaccessible field was transmitted at such cases. I'm pretty sure Twitter returns something

Anyway my problem has been solved, TY!

**Comment by g8rswimmer** [comment]
Thanks for the update. 

I will look into some better error/logging

**Comment by g8rswimmer** [comment]
@ingwar1991 
Did you try and use `errors.As` to see if the error returned is `TweetErrorResponse` which will have more information about the error response form twitter.

**Comment by ingwar1991** [comment]
Yes, but didn't get error

I've used `switch` construction from example

> 
	fieldOpts := twitter.TweetFieldOptions{
		TweetFields: []twitter.TweetField{
			twitter.TweetFieldCreatedAt,
			twitter.TweetFieldOrganicMetrics,
			twitter.TweetFieldPublicMetrics,
			twitter.TweetFieldNonPublicMetrics,
			twitter.TweetFieldPromotedMetrics,
		},
	}

	lookups, err := tweetApi.Lookup(context.Background(), tweetIds, fieldOpts)
	fmt.Println("response", lookups, err)
	if err != nil {
		fmt.Println("err1", err)
	}

	var tweetErr *twitter.TweetErrorResponse
	switch {
	case errors.As(err, &tweetErr):
		fmt.Println( "err2", err, &tweetErr )
	case err != nil:
		fmt.Println( "err3", err )
	default:
		for _, lookup := range lookups {
			fmt.Println("lookup", lookup)
		}
	}
	
**OUTPUT**
> `response map[] <nil>`
