### ISSUE TITLE
v2: Tweets filtered stream

### ISSUE THREAD

**Issue by g8rswimmer** [g8rswimmer/go-twitter#25]
Add the filtered stream to the v2 library

https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction

**Comment by dnapier** [comment]
Hey, would love to see this implemented. Just gave it half a day and am running into this:

```json
{
  "StatusCode": 429,
  "errors": null,
  "title": "ConnectionException",
  "detail": "This stream is currently at the maximum allowed connection limit.",
  "type": "https://api.twitter.com/2/problems/streaming-connection"
}
```

**Comment by Fallenstedt** [comment]
I have it implemented here. Feel free to use this code as a reference: https://github.com/Fallenstedt/twitter-stream

**Comment by dnapier** [comment]
This is marked as done, but I'm still encountering the issue. Using the v2/_examples code, a successful connection is made, but then disconnects after what I'm assuming is the timeout period elapses. For comparison, I see in python the solution using requests keeps the http connection open and continuously iterates over incoming data. I see there's a heartbeat built into your implementation, but I haven't confirmed it's functionality. Regardless, it seems as though after the timeout hits, the twitter server doesn't recognize that the client is no longer listening and keeps the 'maximum connection limit' met at 1. There seems no way to manually clear this on Twitter's side, not sure how to fix. I appreciate your library though and the work you put into it!

**Comment by g8rswimmer** [comment]
@dnapier For the example, there is a 20 second timer to allow for the connection to end.
https://github.com/g8rswimmer/go-twitter/blob/master/v2/_examples/tweet-search-stream/main.go#L54

I am not sure what problems that you are having.  Would you mind providing an example and what problem you are encountering.

**Comment by dnapier** [comment]
@g8rswimmer Thanks for pointing that out, I realized around the same time that was my mistake. I was copying and pasting your example for testing, but it would drop the connection after 20 seconds. So your code works fantastic, thank you again!

**Comment by cgrinds** [comment]
I also copy/pasted the v2 sample [here](https://github.com/g8rswimmer/go-twitter/blob/6e75086294e89c9a18930ca7cf192ca8b3d03560/v2/_examples/tweets/volume-stream/tweet-sample-stream/main.go).

I changed the timer from 20 seconds to 2 hours, thinking the client code would send a heartbeat and wait for 2h, streaming all tweets matching my previously added rules. 

That's not what happens though. Instead after 20s, the clause at `tweetStream.Connection() == false ` is true and the method returns.

Am I responsible for sending a keep-alive or misunderstood how I should use this library to long-poll for tweets?

**Comment by g8rswimmer** [comment]
@cgrinds 
I used the example [here](https://github.com/g8rswimmer/go-twitter/blob/master/v2/_examples/tweets/volume-stream/tweet-sample-stream/main.go) and also set it for 2 hours.  

It ran for the entire two hours outputting tweets.

From the streaming [documentation](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data) the client might disconnect and you would need to reconnection.

**Comment by cgrinds** [comment]
awesome, thanks for verifying!
