### ISSUE TITLE
404 should report relevant information back to caller

### ISSUE THREAD

**Issue by echarrod** [g8rswimmer/go-twitter#39]
When I call 
```go
lookups, err := tweet.FilteredStream(context.Background(), fieldOpts)
```

In tweet.go the call:
```go
err := decoder.Decode(e);
```
returns `invalid character '<' looking for beginning of value`

This is then passed up to the caller of .FilteredStream, with the error being `tweet lookup response error decode: invalid character '<' looking for beginning of value`

This isn't a very meaningful error, I think it should be relayed to the user that a 404 has occurred.

Information:
req: `GET https://api.twitter.com//2/tweets/search/stream`
resp.Status: `404 Not Found`

**Comment by g8rswimmer** [comment]
Looks like there are a couple of bugs, that need addressing

1. The endpoint is not correct as it has a `//` 
2. the 404 response is XML and causes an error.  A better one, as suggested is needed.
