### ISSUE TITLE
Drop me a line?

### ISSUE THREAD

**Issue by andypiper** [g8rswimmer/go-twitter#51]
Hi Sean - can you follow or DM me on Twitter? apologies for the weird GH issue reach out :-)

**Comment by g8rswimmer** [comment]
@andypiper Sure, I followed you but was not able to send a DM.

**Comment by andypiper** [comment]
Huh. @andypiper on Twitter?

**Comment by rothgar** [comment]
I can only hope this means this library will get official twitter support :)

**Comment by mholt** [comment]
That would be great. How's that going? I've been struggling to get Oauth2 working with the v2 API so I'm interested in this lib.

**Comment by g8rswimmer** [comment]
@mholt 
Sure are you having any trouble with Oauth2 with this lib?  Maybe create a new issue to help with this.  
I don't have a template but some background and expect behavior can be helpful.

Let me know if I can help.

**Comment by mholt** [comment]
@g8rswimmer Thanks, but no worries, it's not with this lib. I posted my troubles here: https://twittercommunity.com/t/http-400-with-redirect-is-requested-error-description-from-oauth2-authorize-endpoint/164764

**Comment by g8rswimmer** [comment]
@mholt  where did you get the documentation that you referenced in the question you posted?  I am unable to find that endpoint example.

**Comment by mholt** [comment]
@g8rswimmer From here: https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token

When I tried posting it originally it wouldn't let me add links, but I just went back and edited my post and it let me save it, so I added the link to the docs now.

**Comment by samirsss** [comment]
@g8rswimmer - thanks for this wonderful api - this is just because i am impatient and havent done my due diligence. I was just trying to post a tweet using the API using something like this

client := &twitter.Client{
		Authorizer: authorize{
			ConsumerKey:    consumerKey,
			ConsumerSecret: consumerSecret,
			AccessToken:    accessToken,
			TokenSecret:    accessSecret,
		},
		Client: http.DefaultClient,
		Host:   "https://api.twitter.com",
	}

	req := twitter.CreateTweetRequest{
		Text: message,
	}
	fmt.Println("Callout to create tweet callout")

	tweetResponse, err := client.CreateTweet(context.Background(), req)

I am getting a 401 Http Status back. Any quick feedback here? Also it will be great if you have any examples of using Oauth2 authentication, since i think Bearer Token is not allowed to post tweets.

**Comment by andypiper** [comment]
This has gotten way off topic so I'm going to close this issue - @samirsss you can open another one if needed. You might want to check whether your code is hitting the v2 API and if not, whether you have the right access (Essential or Elevated).
